# Generated by Django 3.0.7 on 2020-06-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200629_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
